### PR TITLE
Removing unneeded dependency installation

### LINKED ISSUE #243: APT requirements causing a failure
When using the role on a recent Kali image you would encounter a error during the dependency installation:

```
TASK [ansible-role-visual-studio-code : Install dependencies (apt)] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'gconf2' is available"}
```

Installing most of the dependencies is not necessary at this step and will be handled by apt at the time of installation. Only `ca-certificates` and `apt-transport-https` ar required. I would suggest changing the task to something like this:

```yaml
- name: Install dependencies (apt)
  become: yes
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
    state: present
```

### PR DESCRIPTION
**Pull request by 1337-42**
This PR closes #243 

Installation of the other dependencies will be handled by apt at the time of installing code.

### CODE REVIEW

**Comment by jsf9k** [comment]
I ran into this issue just now.  Thanks to @1337-42 for having already created a PR!

**Review by dav3r — APPROVED** [review]
👍 👍

**Comment by jsf9k** [comment]
@freemanjp - What can we do to help this PR along?

**Review by felddy — APPROVED** [review]
💪

**Comment by jsf9k** [comment]
@freemanjp?  :cry:

**Comment by 1337-42** [comment]
@freemanjp Thanks for merging the PR 🎉

**Comment by freemanjp** [comment]
@1337-42, sorry for the delay (day job keeping me busy). Thanks for the PR, you can find your fix in version [7.0.0](https://github.com/gantsign/ansible-role-visual-studio-code/releases/tag/7.0.0) of this role.

**Pull request merged**
